- name: ssh dir stat
  stat:
    path: ~/.ssh
  register: ssh_dir

- name: ssh dir exists
  when: not ssh_dir.stat.exists
  file:
    path: ~/.ssh
    state: directory

- name: create ssh key
  when: not ssh_dir.stat.exists
  command: pushd ~/.ssh && ssh-keygen -t rsa

- name: add github host
  when: not ssh_dir.stat.exists
  command: ssh-keyscan github.com >> ~/.ssh/known_hosts

- name: scripts dir stat
  stat:
    path: ~/scripts
  register: scrips_dir

- name: scripts dir exists
  when: not scrips_dir.stat.exists
  file:
    path: ~/scripts
    state: directory

- name: add git completion script
  copy:
    src: git-completion.bash
    dest: ~/scripts/git-completion.bash

- name: add bash profile
  copy:
    src: bash_profile
    dest: ~/.bash_profile



